all: clean build run

clean: # remove data and binary folder

build: # compile to binary (if you use interpreter, then do not implement it)

run: python3 src/scraper.py --y youtubeid --o outputfilename
